version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: lms
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
  web:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysqldb